# Generated by Django 4.0.3 on 2022-11-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinInfoBTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.CharField(max_length=10)),
                ('tp', models.IntegerField()),
                ('scr', models.FloatField()),
                ('tv', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CoinInfoDKA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.CharField(max_length=10)),
                ('tp', models.IntegerField()),
                ('scr', models.FloatField()),
                ('tv', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CoinInfoDOGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.CharField(max_length=10)),
                ('tp', models.IntegerField()),
                ('scr', models.FloatField()),
                ('tv', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CoinInfoETH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.CharField(max_length=10)),
                ('tp', models.IntegerField()),
                ('scr', models.FloatField()),
                ('tv', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CoinInfoXRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.CharField(max_length=10)),
                ('tp', models.IntegerField()),
                ('scr', models.FloatField()),
                ('tv', models.FloatField()),
            ],
        ),
    ]
