# Generated by Django 4.0.3 on 2022-11-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinboard',
            name='write_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
